// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwT7_RA5j1TgFa-QwleleDRkZ_TiYAGpI',
    appId: '1:1056854110136:web:133a286570002f7050a94d',
    messagingSenderId: '1056854110136',
    projectId: 'chatburst-5eea4',
    authDomain: 'chatburst-5eea4.firebaseapp.com',
    databaseURL: 'https://chatburst-5eea4-default-rtdb.firebaseio.com',
    storageBucket: 'chatburst-5eea4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhsBF-Sh2mNNoHDgTHIii9aT1kJk3ERrY',
    appId: '1:1056854110136:android:781e561dbc20527050a94d',
    messagingSenderId: '1056854110136',
    projectId: 'chatburst-5eea4',
    databaseURL: 'https://chatburst-5eea4-default-rtdb.firebaseio.com',
    storageBucket: 'chatburst-5eea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdOCbc1JOtdM1ZX10fxV8HJ26wkE7wW4',
    appId: '1:1056854110136:ios:ef4df90e6ad0a04e50a94d',
    messagingSenderId: '1056854110136',
    projectId: 'chatburst-5eea4',
    databaseURL: 'https://chatburst-5eea4-default-rtdb.firebaseio.com',
    storageBucket: 'chatburst-5eea4.appspot.com',
    iosBundleId: 'com.example.chatburst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdOCbc1JOtdM1ZX10fxV8HJ26wkE7wW4',
    appId: '1:1056854110136:ios:ef4df90e6ad0a04e50a94d',
    messagingSenderId: '1056854110136',
    projectId: 'chatburst-5eea4',
    databaseURL: 'https://chatburst-5eea4-default-rtdb.firebaseio.com',
    storageBucket: 'chatburst-5eea4.appspot.com',
    iosBundleId: 'com.example.chatburst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwT7_RA5j1TgFa-QwleleDRkZ_TiYAGpI',
    appId: '1:1056854110136:web:3dab971be863782c50a94d',
    messagingSenderId: '1056854110136',
    projectId: 'chatburst-5eea4',
    authDomain: 'chatburst-5eea4.firebaseapp.com',
    databaseURL: 'https://chatburst-5eea4-default-rtdb.firebaseio.com',
    storageBucket: 'chatburst-5eea4.appspot.com',
  );

}